In [32]:
 import pandas as pd
import numpy as np

In [33]:
data = {
    "Patient_ID": [1, 2, 3, 4, 5],
    "Age": [25, 40, 35, 60, 50],
    "Blood_Pressure": [120, 140, 130, 150, 145],
    "Diabetes": ["No", "Yes", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)

In [34]:
df

   Patient_ID  Age  Blood_Pressure Diabetes
0           1   25             120       No
1           2   40             140      Yes
2           3   35             130       No
3           4   60             150      Yes
4           5   50             145      Yes

In [35]:
df.head()

   Patient_ID  Age  Blood_Pressure Diabetes
0           1   25             120       No
1           2   40             140      Yes
2           3   35             130       No
3           4   60             150      Yes
4           5   50             145      Yes

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      5 non-null      int64
 1   Age             5 non-null      int64
 2   Blood_Pressure  5 non-null      int64
 3   Diabetes        5 non-null      object
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [37]:
df.describe()

       Patient_ID        Age  Blood_Pressure
count    5.000000   5.000000        5.000000
mean     3.000000  42.000000      137.000000
std      1.581139  13.509256       12.041595
min      1.000000  25.000000      120.000000
25%      2.000000  35.000000      130.000000
50%      3.000000  40.000000      140.000000
75%      4.000000  50.000000      145.000000
max      5.000000  60.000000      150.000000

In [38]:
df["Age"].mean()

42.0

In [39]:
df["Diabetes"].value_counts()

Diabetes
Yes    3
No     2
Name: count, dtype: int64

Average age is 42 with a higher probablity of them having diabetes. Studies inconclusive.